### ISSUE TITLE
Question: Does this support RSA (RS256) algorithm?

### ISSUE THREAD

**Issue by mhatrepratik11** [authlete/cbor#9]
**Hello Team.**

Thanks for this library. I am trying to convert JSON payload to COSE and vice versa. I am able to do it with **ES256** but when I try to do it with **RS256**, it ends up with the error **"The algorithm is not supported."**

Please note I am using this dependency with version: **1.15**
```
<dependency>
        <groupId>com.authlete</groupId>
	<artifactId>cbor</artifactId>
	<version>1.15</version>
</dependency>
```

Please see error below:
```
Caused by: com.authlete.cose.COSEException: The algorithm '-257' is not supported.
	at com.authlete.cose.COSESigner.sign(COSESigner.java:199) ~[cbor-1.15.jar:na]
	at com.authlete.cose.COSESigner.sign(COSESigner.java:137) ~[cbor-1.15.jar:na]
	at com.authlete.cose.COSESigner.sign(COSESigner.java:102) ~[cbor-1.15.jar:na]
```

**Seems the RSA algorithm is not supported yet. If not, Is there any future plan to support?**

**Comment by TakahikoKawasaki** [comment]
Thank you for trying using this library. I'm sorry it's difficult for me to spare time to work on RS256 for now, but a PR to support other algorithms is welcome!

**Comment by mhatrepratik11** [comment]
Thank for the reply and clarification @TakahikoKawasaki. I will have a look at it.
